// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdn7J5sxQJ3Ipac3gOCMNpk1SRr9V-jOg',
    appId: '1:218698886631:web:afc76e37775c857245e142',
    messagingSenderId: '218698886631',
    projectId: 'mi-tienda-flutter',
    authDomain: 'mi-tienda-flutter.firebaseapp.com',
    storageBucket: 'mi-tienda-flutter.firebasestorage.app',
    measurementId: 'G-5R2YF1DBXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6xKKt9O5DkvQLdpSU93lxmKegmSfNMgQ',
    appId: '1:218698886631:android:3b9c227ddf37351345e142',
    messagingSenderId: '218698886631',
    projectId: 'mi-tienda-flutter',
    storageBucket: 'mi-tienda-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHwQh-mNRdLUF6VuIb4zjgVI-NqiSQxWU',
    appId: '1:218698886631:ios:7ebae32d60e8c92845e142',
    messagingSenderId: '218698886631',
    projectId: 'mi-tienda-flutter',
    storageBucket: 'mi-tienda-flutter.firebasestorage.app',
    iosBundleId: 'com.example.miTienda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHwQh-mNRdLUF6VuIb4zjgVI-NqiSQxWU',
    appId: '1:218698886631:ios:7ebae32d60e8c92845e142',
    messagingSenderId: '218698886631',
    projectId: 'mi-tienda-flutter',
    storageBucket: 'mi-tienda-flutter.firebasestorage.app',
    iosBundleId: 'com.example.miTienda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdn7J5sxQJ3Ipac3gOCMNpk1SRr9V-jOg',
    appId: '1:218698886631:web:ac15815acf28da5b45e142',
    messagingSenderId: '218698886631',
    projectId: 'mi-tienda-flutter',
    authDomain: 'mi-tienda-flutter.firebaseapp.com',
    storageBucket: 'mi-tienda-flutter.firebasestorage.app',
    measurementId: 'G-CTNVHXPXD8',
  );
}
